[build]
  publish = "."

[[edge_functions]]
  path     = "/data"
  function = "data"

[[edge_functions]]
  path     = "/data.html"
  function = "data-page"

# Add this new route
[[edge_functions]]
  path     = "/data.json"
  function = "data"
